### ISSUE TITLE
Add old people to specific messaging groups upon signup

### ISSUE THREAD

**Issue by barryclark** [DoSomething/mbc-registration-oldpeople#1]
**NOTE**: This issue and repo will be deleted when the final solution is implemented. See the associated issues in the message thread for the final solution.

When an old person signs up, they don't need to be added to our regular weekly blasts or mobile commons, instead they should be added to the old people MailChimp list that April maintains.

A "old person" (26 and 26+) should:

- not be added to the DoSomething Members list in MailChimp (mailchimp_list_id not equal to 71893)
- be added to the Old People / 26+ Club MailChimp list (mailchimp_list_id equal to 80825) and "General" interest_groups:
- Do not add to Mobile Commons
- Send a confirmation transactional email to the old person confirming they have been subscribed to the 26+ Club list. 

**Related**:
https://github.com/DoSomething/dosomething/issues/4058

**Comment by DeeZone** [comment]
@barryclark @sergii-tkachenko

Thinking this through a bit more it makes the most sense to keep the logic that manages the functionality you've outlined above in the DoSomething application (`dosomething_mbp`). The logic is DoSomething specific that if needing to be adjusted in the future should not be scattered in parts of the Message Broker system.

If @sergii-tkachenko agrees then lets move this issue to the DS repo.

A "old person" (26 and 26+) should:
- not be added to the DoSomething Members list in MailChimp (mailchimp_list_id not equal to 71893)
- be added to the Old People / 26+ Club MailChimp list (mailchimp_list_id equal to 80825) and one of the following `interest_groups`:
  - Relationship to DoSomething
  - Partners
  - Events
  - General (I assume this is the correct interest group for DS registrations that are over aged?)
  - Campaigns
  - Salesforce
- Not be added to Mobile Commons general `opt_in_path_id` (is there an alternative `opt_in_path_id` they should be going into? (mbc-registration-mobile - `opt_in_path_id`)

** Note, there are questions in this description that need answering.

**Comment by barryclark** [comment]
I'll speak with April about those and get back to you @DeeZone.

**Comment by barryclark** [comment]
@DeeZone 

- The correct interest_group to add them to is indeed General.
- There isn't an alternative Mobile Commons opt_in path we should use. We can just not add them to Mobile Commons.

**Comment by barryclark** [comment]
@DeeZone 

We'd like to also send a confirmation email to the old person :smile: after they get subscribed to the list. Would that be done in the MailChimp list, or is that something that you need to set up in Mandrill?

**Comment by barryclark** [comment]
@DeeZone 

Also wondering if it's possible to add old people to the Weekly Do emails without adding them to the Members List?

We can break this out into separate issues in future if needed, just logging all of this information in here for now.

**Comment by DeeZone** [comment]
Further to the spec based on details from @barryclark A revised spec:

A "old person" (26 and 26+) should:
- not be added to the DoSomething Members list in MailChimp (mailchimp_list_id not equal to 71893)
- be added to the Old People / 26+ Club MailChimp list (mailchimp_list_id equal to 80825) and one of the following `interest_groups`:
  - General (interest group)
- Not be added to Mobile Commons
- Send a confirmation transactional email to the old person confirming they have been subscribed to the 26+ Club list.  **??** We'll need copy for the email message explaining to the "old person" what it means for them to be on the list.

From @barryclark :
> Also wondering if it's possible to add old people to the Weekly Do emails without adding them to the Members List?

The "Weekly Do" emails is generated from the DoSomething Members list. **??** I suspect a separate mailout would need to be sent to the "26+ Club" list using the same template sent to the "DoSomething Members" list. @ariel would be able to answer this better.

**Note**, there are questions in this description that need answering that are marked with "**??**".

**Comment by DeeZone** [comment]
@barryclark More questions for you on this topic:

With all email now running through Message Broker as of today @sergii-tkachenko raised an important consideration:

What is the logic for assigning email addresses to MailChimp lists:
- DoSomething Members
- 26+ Club
- International

Currently all user registrations are being added to the DoSomething Members list. There's a proposed enhancement to the Message Broker system to filter registrations by birthdate to add older users to the 26+ Club list.

**?? This leaves the questions**:

- Should international registrations on the affiliate sites be added to the DoSomething Members and / or  International list?
- Should affiliate site signups for users 26+ be added to the 26+ Club and / or the International list?

**Comment by DeeZone** [comment]
From Marah:
```
This all makes sense! 

- Being 26+ year of age ---> 26+ Club LIST
- Signup from one of the affiliate websites ---> International LIST
- A regular signup ---> DoSomething Members LIST 

International 26+ is a great point, but yes I think an edge case. My vote would be to put them on the International List and handle later. Unless we can put them in a 26+ group in the International List?
```

**Comment by ArielSD** [comment]
@barryclark and @DeeZone Campaigns (emails) through MailChimp can only be sent within one List. The Weekly Do sends to the "DoSomething Members" List. For "Old People" to get the Weekly Do, we could and would have to send an exact clone of the campaign to the 26+ Club, which is a list in MailChimp itself.

**Comment by DeeZone** [comment]
@barryclark One last outstanding details for this item:
```
Send a confirmation transactional email to the old person confirming they have been subscribed to the 26+ Club list.
```
> We'll need copy for the email message explaining to the "old person" what it means for them to be on the list.

**Comment by DeeZone** [comment]
@barryclark For your reference, a message template to work from:
![image](https://cloud.githubusercontent.com/assets/2119264/5967737/3658701c-a7de-11e4-9331-426fc81a8c8b.png)

**Comment by DeeZone** [comment]
**NOTE**: This issue and repo will be deleted when the final solution is implemented. See the associated issues in the message thread above ^^ for the final solution.
